[project]
name = "api-blog"
version = "0.1.0"
description = ""
authors = [
    {name = "Yaroslav Bordovoy",email = "yaroslavbordovoy@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
